$kind: http-request
name: Configure PayHere
method: POST
url: '{{admin_base_url}}/system-config/payment-gateways/payhere'
order: 3000
headers:
  - key: Content-Type
    value: application/json
body:
  type: json
  content: |-
    {
      "merchantId": "your-payhere-merchant-id",
      "merchantSecret": "your-payhere-merchant-secret",
      "sandbox": true
    }
