$kind: http-request
name: Configure Zoom
method: POST
url: '{{admin_base_url}}/system-config/oauth-apps/zoom'
order: 5000
headers:
  - key: Content-Type
    value: application/json
body:
  type: json
  content: |-
    {
      "clientId": "your-zoom-client-id",
      "clientSecret": "your-zoom-client-secret",
      "redirectUri": "https://your-app.com/auth/zoom/callback"
    }
