using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ONEVO.Infrastructure.Migrations;

public partial class AddAttendanceReadModel : Migration
{
    private static readonly string[] TenantTables = ["attendance_records", "presence_sessions", "break_records"];
    protected override void Up(MigrationBuilder m)
    {
        m.CreateTable(name: "attendance_records", columns: t => new { id=t.Column<Guid>("uuid",nullable:false), tenant_id=t.Column<Guid>("uuid",nullable:false), employee_id=t.Column<Guid>("uuid",nullable:false), date=t.Column<DateOnly>("date",nullable:false), expected_working_day=t.Column<bool>("boolean",nullable:false), work_time_type=t.Column<string>("character varying(20)",maxLength:20,nullable:true), scheduled_start=t.Column<TimeOnly>("time without time zone",nullable:true), scheduled_end=t.Column<TimeOnly>("time without time zone",nullable:true), required_work_minutes=t.Column<int>("integer",nullable:true), expected_work_area=t.Column<string>("character varying(10)",maxLength:10,nullable:true), schedule_timezone=t.Column<string>("character varying(50)",maxLength:50,nullable:true), is_holiday=t.Column<bool>("boolean",nullable:false), holiday_name=t.Column<string>("character varying(100)",maxLength:100,nullable:true), actual_start=t.Column<DateTimeOffset>("timestamp with time zone",nullable:true), actual_end=t.Column<DateTimeOffset>("timestamp with time zone",nullable:true), worked_minutes=t.Column<int>("integer",nullable:false), break_minutes=t.Column<int>("integer",nullable:false), late_minutes=t.Column<int>("integer",nullable:true), attendance_source=t.Column<string>("character varying(20)",maxLength:20,nullable:true), status=t.Column<string>("character varying(30)",maxLength:30,nullable:false), created_at=t.Column<DateTimeOffset>("timestamp with time zone",nullable:false), updated_at=t.Column<DateTimeOffset>("timestamp with time zone",nullable:false) }, constraints: c=>c.PrimaryKey("pk_attendance_records",x=>x.id));
        m.CreateTable(name: "presence_sessions", columns: t => new { id=t.Column<Guid>("uuid",nullable:false), tenant_id=t.Column<Guid>("uuid",nullable:false), employee_id=t.Column<Guid>("uuid",nullable:false), date=t.Column<DateOnly>("date",nullable:false), first_seen_at=t.Column<DateTimeOffset>("timestamp with time zone",nullable:true), last_seen_at=t.Column<DateTimeOffset>("timestamp with time zone",nullable:true), total_present_minutes=t.Column<int>("integer",nullable:false), total_break_minutes=t.Column<int>("integer",nullable:false), source=t.Column<string>("character varying(20)",maxLength:20,nullable:true), status=t.Column<string>("character varying(20)",maxLength:20,nullable:true), created_at=t.Column<DateTimeOffset>("timestamp with time zone",nullable:false), updated_at=t.Column<DateTimeOffset>("timestamp with time zone",nullable:false) }, constraints: c=>c.PrimaryKey("pk_presence_sessions",x=>x.id));
        m.CreateTable(name: "break_records", columns: t => new { id=t.Column<Guid>("uuid",nullable:false), tenant_id=t.Column<Guid>("uuid",nullable:false), employee_id=t.Column<Guid>("uuid",nullable:false), break_start=t.Column<DateTimeOffset>("timestamp with time zone",nullable:false), break_end=t.Column<DateTimeOffset>("timestamp with time zone",nullable:true), break_type=t.Column<string>("character varying(30)",maxLength:30,nullable:true), auto_detected=t.Column<bool>("boolean",nullable:false), created_at=t.Column<DateTimeOffset>("timestamp with time zone",nullable:false) }, constraints: c=>c.PrimaryKey("pk_break_records",x=>x.id));
        m.CreateIndex("ix_attendance_records_tenant_employee_date","attendance_records",new[]{"tenant_id","employee_id","date"},unique:true); m.CreateIndex("ix_presence_sessions_tenant_employee_date","presence_sessions",new[]{"tenant_id","employee_id","date"},unique:true); m.CreateIndex("ix_break_records_tenant_employee_start","break_records",new[]{"tenant_id","employee_id","break_start"});
        foreach(var table in TenantTables) m.Sql($"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY; ALTER TABLE {table} FORCE ROW LEVEL SECURITY; DROP POLICY IF EXISTS tenant_isolation ON {table}; CREATE POLICY tenant_isolation ON {table} USING (current_setting('app.tenant_context_mode', true) = 'admin' OR (current_setting('app.tenant_context_mode', true) = 'tenant' AND tenant_id::text = current_setting('app.current_tenant_id', true))) WITH CHECK (current_setting('app.tenant_context_mode', true) = 'admin' OR (current_setting('app.tenant_context_mode', true) = 'tenant' AND tenant_id::text = current_setting('app.current_tenant_id', true))); ");
    }
    protected override void Down(MigrationBuilder m) { foreach(var table in TenantTables) m.Sql($"DROP POLICY IF EXISTS tenant_isolation ON {table}; ALTER TABLE {table} DISABLE ROW LEVEL SECURITY;"); m.DropTable("break_records"); m.DropTable("presence_sessions"); m.DropTable("attendance_records"); }
}
